model:
  # Model Configuration
  name: "CCE.minilm"
  encoder: "sentence-transformers/all-MiniLM-L12-v2" # Hugging Face model
  architecture: "CrossContextSimilarityModule"
  huggingface: False
  wrapper: ~
  d_attn: ~
  drop_attn: ~
  drop_cls: ~
  fine_tune: False
  max_len: 512


data:
  # Directory Paths
  data: "data/test.json"
  output: "output/"
  input_tags:
    - "full_context"
    - "example_sentence"
  label_tag: "average"
  eval_tags:
    judged_meaning: 
      - "DEFN"


evaluation:
  # Pretrained Model Path and Task
  prev_path: "top_models/cce-all-MiniLM-L12-v2.safetensors"
  task: "eval"
