model:
  # Model Configuration
  name: "SER-deberta"
  encoder: "microsoft/deberta-v3-base" # Hugging Face model
  architecture: "SynonymModel"
  wrapper: "ScoredSynonymModel"
  hidden_sizes:
    - 50
  d_attn: 768
  drop_attn: 0.4
  drop_cls: 0.3
  fine_tune: false
  max_len: 512


data:
  # Directory Paths
  data: "data/test.json"
  output: "output/"
  input_tags:
    - "full_context"
    - "homonym"
    - "judged_meaning"
  label_tag: "average"
  eval_tags: {}


evaluation:
  # Pretrained Model Path and Task
  prev_path: "checkpoint/SER_deberta-v3-base/20260202_201041/SER_deberta-v3-base_2.safetensors"
  task: "eval"
  
  # Training Parameters
  train_batch_size: 64
  epochs: 100
  warmup_ratio: 0.05
  scheduler_type: "cosine"  # Options: linear, cosine, constant
