model:
  # Model Configuration
  name: "DXA"
  encoder: "microsoft/deberta-v3-base" # Hugging Face model
  architecture: "GeneralistModel"
  wrapper: "GeneralistModelScored"
  huggingface: False
  d_attn: 768
  drop_attn: 0.4
  drop_cls: 0.3
  max_len: 512

data:
  # Directory Paths
  data: "data/test.json"
  output: "output/"
  input_tags:
    - "full_context"
    - "example_sentence"
  label_tag: "average"


evaluation:
  # Pretrained Model Path and Task
  prev_path: "top_models/cce-all-mpnet-base-v2.safetensors"
  task: "eval"
