model:
  # Model Configuration
  name: "ft-DXA"
  encoder: "microsoft/deberta-v3-base" # Hugging Face model
  architecture: "GeneralistModel"
  wrapper: "GeneralistModelScored"
  hidden_sizes:
    - 50
  d_attn: 768
  drop_attn: 0.4
  drop_cls: 0.3
  fine_tune: false
  max_len: 512


data:
  # Directory Paths
  root_dir: "none"
  train_data: "data/train_augmented.json"
  val_data: "data/dev_augmented.json"
  input_tags:
    - "source"
    - "target"
  label_tag: "probs"
  metric_tag: "interval"


training:
  # Pretrained Model Path
  prev_path: "checkpoint/DXA_deberta-v3-base/20260129_104921/DXA_deberta-v3-base_2.safetensors"  # Use null for training from scratch, or path/repo for fine-tuning
  task: "classifier-ft"
  
  # Training Parameters
  train_batch_size: 64
  epochs: 100
  warmup_ratio: 0.05
  scheduler_type: "cosine"  # Options: linear, cosine, constant
  
  # Loss Function Configuration
  loss_type: "KLDivLoss"
  loss_betas:
    - 0.7
    - 0.999
  loss_reduction: "batchmean"
  masking: 1
  
  # Learning Rate and Weight Decay
  param_groups:
    encoder:
      layers:
        - model.model
      lr: !!float 1e-5
      weight_decay: 0.1
    attn:
      layers:
        - K
        - Q
        - V
      lr: !!float 5e-5
      weight_decay: 0.1
  lr_others: !!float 3e-5
  weight_decay_encoder: 0.1
  weight_decay_other: 0.01
  
  # Checkpoint Management
  save_total_limit: 3  # Maximum number of checkpoints to save
  
  # Advanced Training Settings
  size_sup: -1
  shuffle: true
  random_drop: true
  
  freeze_components:
    0:
      freeze:
        - base_model
        - classifier.layers.0
      unfreeze:
        - classifier.layers.1
    1:
      freeze: []
      unfreeze:
        - classifier.layers.0
    2:
      freeze: []
      unfreeze:
        - K
        - V
        - Q
    3:
      freeze: []
      unfreeze:
        - LayerNorm
        - rel_embeddings
    4:
      freeze: []
      unfreeze:
        - encoder.layer.11
    5:
      freeze: []
      unfreeze:
        - encoder.layer.10
    6:
      freeze: []
      unfreeze:
        - encoder.layer.9
    7:
      freeze: []
      unfreeze:
        - encoder.layer.8
    8:
      freeze: []
      unfreeze:
        - encoder.layer.7
    9:
      freeze: []
      unfreeze:
        - encoder.layer.6
    10:
      freeze: []
      unfreeze:
        - encoder.layer.5
    11:
      freeze: []
      unfreeze:
        - encoder.layer.4
    12:
      freeze: []
      unfreeze:
        - encoder.layer.3
    13:
      freeze: []
      unfreeze:
        - encoder.layer.2
    14:
      freeze: []
      unfreeze:
        - encoder.layer.1
    15:
      freeze: []
      unfreeze:
        - encoder.layer.0
    16:
      freeze: []
      unfreeze:
        - model.embeddings