model:
  # Model Configuration
  name: "SER"
  encoder: "distilbert/distilbert-base-cased" # Hugging Face model
  architecture: "SynonymModel"
  wrapper: "ScoredSynonymModel"
  hidden_sizes:
    - 50
  d_attn: 768
  drop_attn: 0.4
  drop_cls: 0.3
  fine_tune: false
  max_len: 512


data:
  # Directory Paths
  data: "data/test.json"
  output: "output/"
  input_tags:
    - "full_context"
    - "homonym"
    - "judged_meaning"
  label_tag: "average"


evaluation:
  # Pretrained Model Path and Task
  prev_path: "checkpoint/SER_distilbert-base-cased/20260202_161911/SER_distilbert-base-cased_1.safetensors"
  task: "eval"
  
  # Training Parameters
  train_batch_size: 64
  epochs: 100
  warmup_ratio: 0.05
  scheduler_type: "cosine"  # Options: linear, cosine, constant
