model:
  # Model Configuration
  name: "DXA-bert"
  encoder: "google-bert/bert-base-cased" # Hugging Face model
  architecture: "DXAModel"
  wrapper: "ScoredDXAModel"
  huggingface: False
  d_attn: 768
  hidden_sizes:
    - 50
  drop_attn: 0.4
  drop_cls: 0.3
  max_len: 512

data:
  # Directory Paths
  data: "data/test.json"
  output: "output/"
  input_tags:
    - "full_context"
    - "judged_meaning"
  label_tag: "average"
  eval_tags: {}


evaluation:
  # Pretrained Model Path and Task
  prev_path: "checkpoint/ft-DXA_bert-base-cased/20260130_143443/ft-DXA_bert-base-cased_2.safetensors"
  task: "eval"
