model:
  # Model Configuration
  name: "DefX-distilbert"
  encoder: "distilbert/distilbert-base-cased" # Hugging Face model
  architecture: "GeneralistModel"
  wrapper: "PretrainedGeneralistModel"
  hidden_sizes:
    - 50
  d_attn: 768
  drop_attn: 0.4
  drop_cls: 0.3
  fine_tune: false
  max_len: 512


data:
  # Directory Paths
  root_dir: "none"
  train_data: "data/pretraining/train_augmented.json"
  val_data: "data/pretraining/dev_augmented.json"
  input_tags:
    - "source"
    - "target"
  label_tag: "mask"
  metric_tag: "mask"


training:
  # Pretrained Model Path
  prev_path: null  # Use null for training from scratch, or path/repo for fine-tuning
  
  # Training Parameters
  train_batch_size: 64
  epochs: 100
  warmup_ratio: 0.05
  scheduler_type: "cosine"  # Options: linear, cosine, constant
  
  # Loss Function Configuration
  loss_type: "CrossEntropyLoss"
  loss_betas:
    - 0.7
    - 0.999
  loss_reduction: "mean"
  masking: 1
  
  # Learning Rate and Weight Decay
  lr_encoder: !!float 1e-5
  lr_attn: !!float 5e-5
  lr_others: !!float 3e-5
  weight_decay_encoder: 0.1
  weight_decay_other: 0.01
  
  # Checkpoint Management
  save_total_limit: 3  # Maximum number of checkpoints to save
  
  # Advanced Training Settings
  size_sup: -1
  shuffle: true
  random_drop: true
  
  freeze_components:
    0:
      freeze:
        - classifier
      unfreeze: []

