early_terminate:
  min_iter: 10
  type: hyperband
method: bayesian
metric:
  goal: minimize
  name: valid_loss
parameters:
  architecture:
    distribution: constant
    value: GeneralistModel_nosep
  batch_size:
    values:
    - 32
    - 64
    - 128
    - 256
  d_attn:
    values:
    - 8
    - 16
    - 32
  dev_data:
    distribution: constant
    value: data/pretraining/dev_augmented.json
  drop_attn:
    values:
    - 0.2
    - 0.3
    - 0.4
  drop_cls:
    values:
    - 0.2
    - 0.3
    - 0.4
  encoder:
    distribution: categorical
    values:
    - google-bert/bert-base-cased
    - FacebookAI/roberta-base
    - distilbert/distilbert-base-cased
    - microsoft/deberta-v3-base
  epochs:
    value: 50
    distribution: constant
  freeze_encoder:
    values:
    - 1
    - 0
  lr_encoder:
    values:
    - 1e-05
    - 3e-05
    - 5e-05
  lr_encoder_pre:
    values:
    - 1e-05
    - 3e-05
    - 5e-05
  lr_others:
    values:
    - 1e-05
    - 3e-05
    - 5e-05
  train_data:
    distribution: constant
    value: data/pretraining/train_augmented.json
  weight_decay_encoder:
    values:
    - 0.1
    - 0.05
    - 0.01
  weight_decay_other:
    values:
    - 0.1
    - 0.05
    - 0.01
  wrapper:
    distribution: constant
    value: PretrainedGeneralistModel
program: main.py