program: main.py
method: random
metric:
  goal: minimize
  name: valid_loss
parameters:
  epochs:
    max: 100
    min: 50
    distribution: int_uniform
  batch_size:
    max: 256
    min: 8
    distribution: int_uniform
  d_attn:
    max: 128
    min: 8
    distribution: int_uniform
  drop_attn:
    max: 0.4
    min: 0.2
    distribution: uniform
  drop_cls:
    max: 0.3
    min: 0.2
    distribution: uniform
  lr_encoder_pre:
    max: 5e-5
    min: 1e-5
    distribution: uniform
  lr_encoder:
    max: 5e-5
    min: 1e-5
    distribution: uniform
  lr_others: 
    max: 5e-5
    min: 3e-5
    distribution: uniform
  weight_decay_encoder:
    max: 0.1
    min: 0.01
    distribution: uniform
  weight_decay_other:
    max: 0.1
    min: 0.01
    distribution: uniform
  wrapper:
    value: PretrainedGeneralistModel
    distribution: constant
  train_data:
    value: data/pretraining/train_augmented.json
    distribution: constant
  dev_data:
    value: data/pretraining/dev_augmented.json
    distribution: constant
  architecture:
    values:
      - GeneralistModel_nosep
      - GeneralistModel
    distribution: categorical
  encoder:
    values:
      - google-bert/bert-base-cased
      - FacebookAI/roberta-base
      - answerdotai/ModernBERT-large
      - distilbert/distilbert-base-cased
      - microsoft/deberta-v3-base
    distribution: categorical
  freeze_encoder:
    min: 0
    max: 1
    distribution: int_uniform
early_terminate:
  type: hyperband
  min_iter: 10
